output_root = rf'/media/predator/totem/jizheng/ocelot2023/submit_test'
# target = rf'liner_3_e17_set'
# target = rf'normal'
# target = rf'wentai'
# target=rf'liner'
# target = rf'weighter'
target = 'xuge'
